name: Playwright Tests
on: [push, workflow_dispatch]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm' # This will now work because we have package-lock.json

      - name: Install dependencies
        run: npm ci  # Use 'npm ci' instead of 'npm install' for CI - it's faster and more reliable

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        timeout-minutes: 5  # Add timeout specifically for tests

      - name: Upload test report
        if: always()  # Upload report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7